# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./hack/make/completions

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# gomod:
#   proxy: true

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: darwin
    dir: cmd/apfs
    binary: apfs
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/blacktop/go-apfs/cmd/apfs/cmd.AppVersion={{.Version}} -X github.com/blacktop/go-apfs/cmd/apfs/cmd.AppBuildCommit={{.Commit}}
universal_binaries:
  - id: darwin
    replace: true
    name_template: "apfs"
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "ios" }}iOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - completions/*
checksum:
  name_template: "checksums.darwin.txt"
  disable: false
signs:
  - artifacts: checksum
brews:
  - name: apfs
    repository:
      owner: blacktop
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/blacktop/go-apfs"
    description: "APFS parser written in pure Go"
    install: |
      bin.install "apfs"
      bash_completion.install "completions/_bash" => "apfs"
      zsh_completion.install "completions/_zsh" => "_apfs"
      fish_completion.install "completions/_fish" => "apfs.fish"
    test: |
      system "#{bin}/apfs --version"
changelog:
  sort: asc
  use: github
  groups:
    - title: Dependency updates
      regexp: '^.*?(.+)\(deps\)!?:.+$'
      order: 300
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 100
    - title: "Security updates"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 150
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 200
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 400
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 400
    - title: Other work
      order: 9999
  filters:
    include:
      - "^feat.*"
      - "^fix.*"
      - "^chore.*"
      - "^sec.*"
      - "^(doc|docs).*"
release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/go-apfs/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Read the [documentation](https://blacktop.github.io/ipsw)
    - Follow us on [Twitter](https://twitter.com/blacktop__)
    - Follow us on [Mastodon](https://mastodon.social/@blacktop)