# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - ./hack/make/completions
builds:
  - main: ./cmd/apfs
    id: amd64
    binary: apfs
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
  - main: ./cmd/apfs
    id: arm64
    binary: apfs
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
archives:
  - name_template: >-
      apfs_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "ios" }}iOS
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE
      - completions/*

checksum:
  name_template: "checksums.linux.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch

nfpms:
  - id: packages
    homepage: https://github.com/blacktop/go-apfs
    description: |-
      APFS parser written in pure Go.
    maintainer: Blacktop <https://github.com/blacktop>
    license: MIT
    vendor: Blacktop
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/_bash
        dst: /usr/share/bash-completion/completions/apfs
        file_info:
          mode: 0644
      - src: ./completions/_fish
        dst: /usr/share/fish/completions/apfs.fish
        file_info:
          mode: 0644
      - src: ./completions/_zsh
        dst: /usr/share/zsh/vendor-completions/_apfs
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/apfs/copyright
        file_info:
    file_name_template: >-
      apfs_{{ .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - apk
      - deb
      - rpm
