# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - ./.hack/make/completions
builds:
  - id: darwin
    main: ./cmd/apfs
    binary: apfs
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
universal_binaries:
  - id: darwin
    replace: true
    name_template: "apfs"
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      all: universal
    name_template: "apfs_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
checksum:
  name_template: "checksums.darwin.txt"
  disable: false
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: apfs
    tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/go-apfs"
    description: "APFS parser written in pure Go"
    install: |
      bin.install "apfs"
      bash_completion.install "completions/_bash" => "apfs"
      zsh_completion.install "completions/_zsh" => "_apfs"
      fish_completion.install "completions/_fish" => "apfs.fish"
    test: |
      system "#{bin}/apfs --version"
changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features and updates"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other work
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - '^chore:'
      - "^bumping"
      - "^Update"
      - "^Delete"
      - "^Working"
      - "reorg"
      - "updates"
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
release:
  footer: |
    ### Summary
    **Full Changelog**: https://github.com/blacktop/ipsw/compare/{{ .PreviousTag }}...{{ .Tag }}
    ## What to do next?
    - Follow us on [Twitter](https://twitter.com/blacktop__)